import Head from "next/head";
import { Inter } from "next/font/google";
import classes from "styles/Home.module.css";
import { Links } from "components/Links";
import { Main } from "components/Main";
import { Header } from "components/Header";
import { useCounter } from "hooks/useCounter";
import { useInputArray } from "hooks/useInputArray";
import { useBgLightBlue } from "hooks/useBgLightBlue";

const inter = Inter({ subsets: ["latin"] });

export default function About() {
  const { count, isShow, handleClick, handleDisplay } = useCounter();
  const { text, array, handleChange, handleAdd } = useInputArray();
  useBgLightBlue();

  return (
    <>
      <Head>
        <title>About page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />

      {isShow ? <h1>{count}</h1> : null}
      <button onClick={handleClick}>ボタン</button>
      <button onClick={handleDisplay}>{isShow ? "非表示" : "表示"}</button>

      <input type="text" value={text} onChange={handleChange} />
      <button onClick={handleAdd}>追加</button>
      <ul>
        {array.map((item) => {
          return <list key={item}>{item}</list>;
        })}
      </ul>

      <main className={`${classes.main} ${inter.className}`}>
        <Main page="about" />

        <Links />
      </main>
    </>
  );
}
