import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Links } from "../components/links";
import {Headline} from "../components/Headline";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>About page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Headline title="About page" />

        <div className={styles.center}>
          <h1 className={styles.title}>
            This is About page!!!
          </h1>
        </div>

        <Links />
      </main>
    </>
  );
}
