import Head from "next/head";
import { Inter } from "next/font/google";
import classes from "styles/Home.module.css";
import { Links } from "components/Links";
import { Main } from "components/Main";
import { Header } from "components/Header";
import { useCallback, useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [count, setCount] = useState(1);

  const handleClick = useCallback(() => {
    if (count < 10)  {
      setCount((prevCount) => prevCount + 1);
    }
  }, [count]);

  const handleDisplay = useCallback(() => {
    setIsShow((prevIsShow) => !prevIsShow);
  }, []);

  useEffect(() => {
    document.body.style.backgroundColor = "lightblue";

    return () => {
      document.body.style.backgroundColor = "";
    };
  }, []);

  return (
    <>
      <Head>
        <title>Index page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />

      <h1>{count}</h1>
      <button href="/about" onClick={handleClick}>
        ボタン
      </button>

      <main className={`${classes.main} ${inter.className}`}>
        <Main page="index" />

        <Links />
      </main>
    </>
  );
}
